### ISSUE TITLE
Providing different sets of values for different build types

### ISSUE THREAD

**Issue by olegosipenko** [zsoltk/paperwork#45] opened 2016-06-19 19:45 UTC
It is usual situation to have different sets of values for debug and production version of application - different Base Urls for example. Also while some values have to differ from one build type to another, other values should be equal. So one should have a way to declare values in different parts of Gradle script.
So I tried to declare paperwork block in `buildTypes` section of my `build.gradle`. But I always get values from `Release` build type in my `paperwork.json` file. Also I tried to add paperwork block in the root of my `build.gradle` for values that common for all build types, but in this case values from `buildTypes` section have not been included in resulting json file.
So, any suggestions how to deal with this?

**Comment by zsoltk** [comment] 2016-07-12 13:27
This is a duplicate of #35 , please see my answer there.

**Closed as completed by zsoltk** 2016-07-12 13:27 UTC

**Comment by olegosipenko** [comment] 2016-07-12 14:33
Sorry, I missed that. Thanks
